name: llm-catalog-search
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - mlflow=2.7.1
  - chromadb=0.4.13
  - langchain=0.0.309
  - sentence-transformers=2.2.2
  - python-dotenv=1.0.0
  - pytorch-cuda=11.8
  - pytorch=2.1.0
  - pyspark=3.5.0
  - typing_inspect=0.9.0
  - typing_extensions=4.8.0
